# Generated by Django 6.0.4 on 2026-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課程名稱')),
                ('teacher', models.CharField(max_length=100, verbose_name='講師')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('description', models.TextField(verbose_name='課程介紹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
